version: "3.8"

networks:
    app-tier:
        driver: bridge
  
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - 3306
        ports:
            - 3306:3306   
        networks:
            - app-tier      
        environment:
            MYSQL_DATABASE: solution
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbuser
            MYSQL_ROOT_HOST: '%'
    backend:
        depends_on:
            - db
        build: 
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - 8080:8080
        networks:
            - app-tier